### ISSUE TITLE
About CVT

### ISSUE THREAD

**Issue by RYHSmmc** [cure-lab/MagicDrive#100]

**Comment by RYHSmmc** [comment]
Hello author, I tested the performance using the weight 224x512 released by you and the road segmentation weight released by CVT. After direct inference, the performance of magicdrive was only 59.0 (61.0 in your paper). I trained CVT 75ep on real data and verified its performance on a real dataset, which was only 72.1. However, your paper's mixed data experiment showed 74. Can you give some suggestions?

**Comment by flymin** [comment]
Please use #93
