### ISSUE TITLE
About DiT Architecture

### ISSUE THREAD

**Issue by jiangchaokang** [cure-lab/MagicDrive#103]
Hello, I would like to commend your work on MagicDrive and its contributions to the autonomous driving field. I've noticed that while Stable Diffusion 3.5 (https://huggingface.co/spaces/stabilityai/stable-diffusion-3.5-medium) has adopted the DiT architecture, your current implementation still uses UNet, which is a relatively older framework and may not perform as well as SD3.5. In your response at https://github.com/cure-lab/MagicDrive/issues/46#issuecomment-2175239101, you mentioned plans to release a DiT architecture version of MagicDrive soon. Do you have any recent updates on this release timeline? I'm looking forward to your response.

**Comment by flymin** [comment]
Our tech report will be on ArXiv this week. Stay tuned.

**Comment by flymin** [comment]
MagicDriveDiT is released. Please check https://gaoruiyuan.com/magicdrivedit/

**Comment by jiangchaokang** [comment]
> MagicDriveDiT is released. Please check https://gaoruiyuan.com/magicdrivedit/

This work is impressive, particularly in several key aspects:

1. Implementation of sophisticated trajectory control
2. Support for higher resolution output
3. Excellent temporal consistency

Based on these features, I believe the model will demonstrate stronger generalization capabilities. When integrated with traffic flow generation models, it could produce a substantial amount of valuable data. **Finally, I'm interested in the open-source timeline for this project, as I'm eager to access the code for further experimentation and development work.**

**Comment by flymin** [comment]
Thanks. We will make it happen as soon as possible. You can open an issue in the new repo and will be notified when the code is ready.
