### ISSUE TITLE
Reproduction of Perception Models

### ISSUE THREAD

**Issue by mrabiabrn** [cure-lab/MagicDrive#107]
Hi,
When I checked the CVT results in Table 1 and Table 3, I noticed a discrepancy. In Table 1, the oracle performance for vehicle segmentation is reported as 33.66, which I understood to be your reproduction of CVT. However, in Table 3, the performance is listed as 36.0, consistent with the original paper. Additionally, it seems that the augmentation performance in Table 3 is added on top of the originally reported results.

Does the increase comes from 33.66 or 36.0? Could you clarify this? 

Thank you

<img width="754" alt="image" src="https://github.com/user-attachments/assets/1d22516e-5f47-4aac-8503-f57d79632c13">
<img width="335" alt="image" src="https://github.com/user-attachments/assets/b1f44247-c45d-45ff-8a51-5dc162ac1e47">

**Comment by flymin** [comment]
33.66 is tested with 224x400 inputs, which are pre-downsampled and upsampled to keep the same pipeline as we test the generated views.

36.00 is from the original settings of CVT, using the raw data from the validation set. Our reproduction matched this performance.

**Comment by flymin** [comment]
If the original CVT setting is 224x448, then yes (I forgot the details of CVT).

We did not change the original data processing pipeline of CVT, which loads from 900x1600 images. Therefore, to use generated views, we upsample and pad to 900x1600 and then go through CVT. Oracle is obtained with 900x1600 -> 224x400 -> 900x1600 -> CVT.

**Comment by mrabiabrn** [comment]
Thank you for the clarification 👍🏻
