### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by CSUXA** [cure-lab/MagicDrive#109]
When I run the demo/run.py,i got an error.
encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by flymin** [comment]
I cannot recall which line of code trigger this error. Please provide the full trace. Thanks.

**Comment by CSUXA** [comment]
![屏幕截图 2024-11-19 200429](https://github.com/user-attachments/assets/e23c06d7-edc2-4525-871e-920163d0d8ae)
![屏幕截图 2024-11-19 200440](https://github.com/user-attachments/assets/a8a9052b-8797-44cd-86d1-c540229182e9)
These two photos contain all the error messages.

**Comment by CSUXA** [comment]
> 我不记得是哪行代码触发了这个错误。请提供完整的跟踪记录。谢谢。

![屏幕截图 2024-11-19 200429](https://github.com/user-attachments/assets/67f23dec-78fb-4472-81dc-135536fd3e50)
![屏幕截图 2024-11-19 200440](https://github.com/user-attachments/assets/28b48ae9-22a2-4471-b080-d4a9c44f215a)
these photos contain all the error messages.

**Comment by flymin** [comment]
It shows the error was raised from transformers package. Please check the package version.

**Comment by CSUXA** [comment]
> It shows the error was raised from transformers package. Please check the package version.

i installed transformers==4.27.4,which is the right version.

**Comment by flymin** [comment]
I did a quick search and find that same issue happens to stable diffusion but did not find useful solution.

May I know what command you are using? And full list of your environment? Please provide as much detail as possible.

**Comment by CSUXA** [comment]
> I did a quick search and find that same issue happens to stable diffusion but did not find useful solution.
> 
> May I know what command you are using? And full list of your environment? Please provide as much detail as possible.

![2ba51c1b7ecafd227c15551207b4733c](https://github.com/user-attachments/assets/97ab6b4a-ba39-4879-8c14-3c6c7363a5ee)
![8c189e10ce0e24c91b5c1ef22dfc7284](https://github.com/user-attachments/assets/62ca5917-196e-4948-84e5-aee743237fed)
![e0b5ce0a61090873290e147dc01a081a](https://github.com/user-attachments/assets/27164ace-009a-4dd5-beee-cda92bf1fe3b)
![c552b189aa2928a3a70bf326f0f9d5ff](https://github.com/user-attachments/assets/f97229c8-2c69-4efd-b350-4c2cde4ab79b)
![5beb589d5ffbe6baf2f2d691cb9db0d3](https://github.com/user-attachments/assets/9debf2ca-226b-4a2b-b3d0-67f46d52dcee)
![5ed4b2cb066cc8c48258463e7bc0c1f3](https://github.com/user-attachments/assets/28a0bfd7-5df4-4b74-b7bb-d740f5d1a8cd)
![5fd60c5a61ebf3db27c02427854e17de](https://github.com/user-attachments/assets/8e5dc4d2-0edc-4361-8316-bfc76c64fa99)
it's the full list of my environment

**Comment by flymin** [comment]
And the full command to run with the full output.

**Comment by CSUXA** [comment]
> 以及要运行完整输出的完整命令。

![1472c3cec64d94ffe3e850e4dbb09a73](https://github.com/user-attachments/assets/d626d9b0-9b14-41ac-ae37-8aa67efabecf)
![d3aa1533d61b6c0e63f4360459f89365](https://github.com/user-attachments/assets/56616884-4626-4a4e-809a-6e4fb7c639d5)
it's the full command to run with the full output.

**Comment by CSUXA** [comment]
i wonder if you have encountered this error as well.can i solve this error by reinstalling the conda environment?

**Comment by flymin** [comment]
No, actually, this error does not seem to be related to our implementation. I didn't find any significant error in the above information. You may also check the downloaded pre-trained models.

**Comment by CSUXA** [comment]
you mean that maybe the error was caused by the pre-trained models?

**Comment by CSUXA** [comment]
> No, actually, this error does not seem to be related to our implementation. I didn't find any significant error in the above information. You may also check the downloaded pre-trained models.

you mean that maybe the error was caused by the pre-trained models?

**Comment by flymin** [comment]
Just copy the title to google. You should be able to find the followings:
https://github.com/ostris/ai-toolkit/issues/70
https://github.com/CompVis/stable-diffusion/issues/860

I do not understand the solution proposed by them, but it seems not to be related with our repo.

**Comment by CSUXA** [comment]
> Just copy the title to google. You should be able to find the followings: [ostris/ai-toolkit#70](https://github.com/ostris/ai-toolkit/issues/70) [CompVis/stable-diffusion#860](https://github.com/CompVis/stable-diffusion/issues/860)
> 
> I do not understand the solution proposed by them, but it seems not to be related with our repo.

I'v seen this,but it doesn't solve the error.

**Comment by flymin** [comment]
Can you try the model from #84?

**Comment by flymin** [comment]
Let me explain. 

The tokenizer should have `model_max_length` from its config, which comes from the stable-diffusion models. However, if there is no `model_max_length` neither `max_len` in the config, the default value would be 
```python
VERY_LARGE_INTEGER = int(1e30)  # This is used to set the max input length for a model with infinite size input
```
which is from the `transformers` package. Therefore, if the wrong is loaded (especially the tokenizer), it may lead to your problem.

The solution is to load the correct model.

**Comment by CSUXA** [comment]
> Let me explain.
> 
> The tokenizer should have from its config, which comes from the stable-diffusion models. However, if there is no neither in the config, the default value would be`model_max_length``model_max_length``max_len`
> 
> ```python
> VERY_LARGE_INTEGER = int(1e30)  # This is used to set the max input length for a model with infinite size input
> ```
> 
> which is from the package. Therefore, if the wrong model is loaded (especially the tokenizer), it may lead to your problem.`transformers`
> 
> The solution is to load the correct model.

thanks,i wil try it .but i wonder which model do you use,where can i choose the model?

**Comment by flymin** [comment]
See my last comment.

**Comment by flymin** [comment]
May I know is your problem resolved?

**Comment by CSUXA** [comment]
> May I know is your problem resolved?

I apologize for being delayed in replying to you due to some personal matters.Thank you very much for your guidance,and my problem has been resolved.
