### ISSUE TITLE
ValueError: xformers is not available. Make sure it is installed correctly

### ISSUE THREAD

**Issue by Dylandtt** [cure-lab/MagicDrive#11]
训练时可以不安装xformers吗

**Comment by flymin** [comment]
Yes, you can disable it [here](https://github.com/cure-lab/MagicDrive/blob/92a85fac7019df8f3251edbde31a027d058b14da/configs/exp/224x400.yaml#L12) or through command line like our demo, but it leads to much more gpu memory cost. You may use fewer bs or lower resolutions if OOM. Besides, we also support gradient checkpointing. Choose your own configurations wisely.
