### ISSUE TITLE
Can I make minor adjustments based on SDv1.5mv-rawbox_2023-09-07_18-39_224x400

### ISSUE THREAD

**Issue by Michael-Yi-Rong** [cure-lab/MagicDrive#112]
If so, how to do it?

**Comment by flymin** [comment]
Please specify your issue in details. Otherwise I cannot help you.

**Comment by Michael-Yi-Rong** [comment]
> Please specify your issue in details. Otherwise I cannot help you.

I have solved the problem mentioned. But I have another question, how can I calculate the mIoU, mAP and NDS of the SDv1.5mv-rawbox I get? Thanks again for your help!

**Comment by flymin** [comment]
In this case, I will close this issue. Please check other issues related to the evaluation process. There are many discussions on it.
