### ISSUE TITLE
About model config

### ISSUE THREAD

**Issue by jspark5638** [cure-lab/MagicDrive#116]
Thank you for your great work!

I have a question.
![Screenshot from 2024-11-22 13-09-18](https://github.com/user-attachments/assets/f081ba3d-6810-46b0-bafa-b857661f62cc)
In this image, 
error message said I don't have config.json file but, the link you attatched in #84 doesn't provide config.json file.
Can I know your what files in your pretrained folder and get a config.json file?

**Comment by jspark5638** [comment]
I want to run a inference code

**Comment by flymin** [comment]
Please read the readme and prepare the pre-trained model accordingly. I don’t want to repeat them and will close this issue. If you have other problems, please feel free to open issues and specify them. Thanks for understanding.
