### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by TJXA** [cure-lab/MagicDrive#117]
![屏幕截图 2024-11-23 210206](https://github.com/user-attachments/assets/ad536807-9394-4ec7-a3ed-aa1ab90103af)
When I run the code:accelerate launch --mixed_precision fp16 --gpu_ids all --num_processes 1 tools/train.py +exp=224x400 runner=default,I got an error like this.I was wondering the reason.I use the mini dataset to generate mmdet3d annotation files,the code is:python ./tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes_mmdet3d_2 --extra-tag nuscenes --version v1.0-mini.
To be specific,the error is:
![image](https://github.com/user-attachments/assets/d2f35500-2954-4f34-9c1c-0347a95d70fc)

**Comment by CSUXA** [comment]
I need your help very much.

**Comment by flymin** [comment]
We randomly pick some indexes in the config for validation. You should be able to find `validation_index` in the config. Change it to contain only values less than 81 (because your val set only contains 81 samples).

**Comment by CSUXA** [comment]
I really appreciate your help,and I have already solved the problem.
