### ISSUE TITLE
How seq-embedding embed to BEV map and put in u-net?

### ISSUE THREAD

**Issue by Michael-Yi-Rong** [cure-lab/MagicDrive#121]
Excuse me, I have a theoretical question about how seq embedding embed to BEV map and put in u-net. I have not gotten the point from the paper, could you please explain it in an easy way? Thanks a lot!
![1733053688143](https://github.com/user-attachments/assets/8f740449-98a6-4914-be0c-00e5802eef69)

**Comment by flymin** [comment]
The implementation is similar to ControlNet. First use cross-attn between seq emb and bev map, then the layer-wise hidden states are added to the upsampling modules.

**Comment by Michael-Yi-Rong** [comment]
> The implementation is similar to ControlNet. First use cross-attn between seq emb and bev map, then the layer-wise hidden states are added to the upsampling modules.

Excuse me, I did not find the cross-attn in codes. Could you show me where, thanks alot.

**Comment by flymin** [comment]
[This line](https://github.com/cure-lab/MagicDrive/blob/d2ab0f753d91d6068ddcf4e9d2fa22fe53a187a6/magicdrive/networks/unet_addon_rawbox.py#L40). You should be able to find the module in diffusers.

**Comment by Michael-Yi-Rong** [comment]
> [This line](https://github.com/cure-lab/MagicDrive/blob/d2ab0f753d91d6068ddcf4e9d2fa22fe53a187a6/magicdrive/networks/unet_addon_rawbox.py#L40). You should be able to find the module in diffusers.

Sorry, I mean, the step that using cross-attn between seq emb and bev map

**Comment by Michael-Yi-Rong** [comment]
> [This line](https://github.com/cure-lab/MagicDrive/blob/d2ab0f753d91d6068ddcf4e9d2fa22fe53a187a6/magicdrive/networks/unet_addon_rawbox.py#L40). You should be able to find the module in diffusers.

I got it, thx
