### ISSUE TITLE
A issue about 'bev_map_with_aux'

### ISSUE THREAD

**Issue by Miayui** [cure-lab/MagicDrive#122]
Hi, thank you for your great work!
Here's a little question about 'bev_map_with_aux'(key from val_input in 'tools/test.py') bothers me: when I didn't generate HD maps beforehand, how could the val_input load the map information?
I've already read the load config "cfg.dataset.data.val" and it seems bev map information loaded from h5 file. But when the h5 file wasn't generates beforehand, is the bev map information loaded by mmdet3d.datasets.build_dataset? How can I find the code associated with loading 'bev_map_with_aux'?
Could you please give me some hints? Thank you so much!

**Comment by flymin** [comment]
see [here](https://github.com/cure-lab/MagicDrive/blob/d2ab0f753d91d6068ddcf4e9d2fa22fe53a187a6/magicdrive/dataset/pipeline.py#L315).

**Comment by Miayui** [comment]
thank you for your help！
