### ISSUE TITLE
where is pretrianed model of unet and controlnet? 

### ISSUE THREAD

**Issue by wang-kangkang** [cure-lab/MagicDrive#123]
i see the pretrained_magicdrive param is : ../MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400 (https://github.com/cure-lab/MagicDrive/blob/video/configs/model/SDv1.5mv_rawbox_t.yaml#L12), but when i download the pretrained-magicdrive-t, i find the name is SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040, am i wrong? Can I just change the configuration path?
another question，when i execute 'scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.3',  it raise error, can't find unet, and can't find controlnet.  
i see unet folder in SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040/weight-E4-S77040/unet, need i change unet_dir(https://github.com/cure-lab/MagicDrive/blob/video/configs/model/SDv1.5mv_rawbox_t.yaml#L30) this to weight-E4-S77040/unet?
and i can't find controlnet, the code raise error from:https://github.com/cure-lab/MagicDrive/blob/video/magicdrive/runner/multiview_t_runner.py#L73  how can i fix these error?
 
translate it to chinese:
我用我看到配置文件中的pretrained_magicdrive参数是: ../MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400 (https://github.com/cure-lab/MagicDrive/blob/video/configs/model/SDv1.5mv_rawbox_t.yaml#L12), 但是下载下来的文件的名字是SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040, 这两个对不上? 我改下配置文件的路径就行吗？
另一个问题，当我执行这个命令去训练的时候'scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.3',  报错了，主要是找不到unet_dir和controlnet_dir所指定的位置
unet文件夹能在下载到的预训练文件夹中找到：SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040/weight-E4-S77040/unet, 只不过路径不对，我是改下unet_dir路径就行吗(https://github.com/cure-lab/MagicDrive/blob/video/configs/model/SDv1.5mv_rawbox_t.yaml#L30) 改成weight-E4-S77040/unet?
然后还会报错找不到controlnet_dir指定的位置, 报错来源于这句代码:https://github.com/cure-lab/MagicDrive/blob/video/magicdrive/runner/multiview_t_runner.py#L73  这些问题我怎么解决?

**Comment by wang-kangkang** [comment]
i know....  the pretrained-model in the video branch is not the pretrained-model which i need, i have to download the pretrained-model in main branch.
video分支这边readme写的预训练模型是video分支训完的，如果想训练视频生成，需要切到图像分支，也即现在的main分支的readme里去下载

**Comment by facethewindha** [comment]
> i know.... the pretrained-model in the video branch is not the pretrained-model which i need, i have to download the pretrained-model in main branch. video分支这边readme写的预训练模型是video分支训完的，如果想训练视频生成，需要切到图像分支，也即现在的main分支的readme里去下载

 你说的预训练是指stable diffusion 1.5还是SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040，我现在在复现视频生成，请问一下生成视频的话可以直接下载video分支而不管main分支吗
