### ISSUE TITLE
TypeError: NuScenesTDataset: __init__() takes from 2 to 14 positional arguments but 15 were given

### ISSUE THREAD

**Issue by wang-kangkang** [cure-lab/MagicDrive#124]
i use a800. i follow the FAQ and execute:
cd third_party/bevfusion
python setup.py develop
after that, i execute "sh scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.3"
it raise: cann't find mmdet3d.  how to fix it?

after that, i execute   cd third_party/bevfusion; python setup.py install.
the mmdet3d is installed, but when i execute train, it raise this bug:

Traceback (most recent call last):
  File "tools/train.py", line 82, in main
    train_dataset = build_dataset(
  File "/anaconda3_a800/lib/python3.8/site-packages/mmdet3d-0.0.0-py3.8-linux-x86_64.egg/mmdet3d/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/anaconda3_a800/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuScenesTDataset: __init__() takes from 2 to 14 positional arguments but 15 were given
how to fix it?

translate to chinese:
我用a800，一开始按照FAQ页面安装a800的环境，特别是在bevfusion文件夹是按照develop方式安装的，但是在执行训练的时候sh scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.3 报错说没有mmdet3d，这是为啥？   
我想不到办法，只能把bevfusion按照python setup.py install 方式安装，这下mmdet3d问题解决了，但是报出来参数错误：TypeError: NuScenesTDataset: __init__() takes from 2 to 14 positional arguments but 15 were given
这下没招了，谁知道我是哪步出错了？

**Comment by flymin** [comment]
I don’t understand. You can find the class definition [here](https://github.com/cure-lab/MagicDrive/blob/cc9d9ae7931b2caf1ba2d304f460ba10e850fa31/magicdrive/dataset/nuscenes_t_dataset.py#L10), which clearly takes more than 15 positional arguments. Did you change the code?

**Comment by wang-kangkang** [comment]
> I don’t understand. You can find the class definition [here](https://github.com/cure-lab/MagicDrive/blob/cc9d9ae7931b2caf1ba2d304f460ba10e850fa31/magicdrive/dataset/nuscenes_t_dataset.py#L10), which clearly takes more than 15 positional arguments. Did you change the code?

i doesn't change the code. i think the keypoint of the problem is environment. the DOC say "where mmdet3d from third_party/bevfusion is not included since we install it with develop mode.", but the train stage raise error if i don't install mmdet3d in bevfusion by execute "python setup.py install", actually the train stage need mmdet3d. how to solve this problem?  can you execute “scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.3” without install mmdet3d？
translate it to chinese：
我觉得问题的关键点还是在环境上。按照对a800的环境安装的做法，就是安装bevfusion那段是不包括mmdet3d的，但是训练的时候我不安装mmdet3d代码就会报错，那不安装mmdet3d肯定不行啊。我只能在bevfusion文件夹里执行python setup.py install，但是这样就跟DOC说明不一致了。我觉得问题在这里，你看能不能帮忙分析下咋回事。  你不安装mmdet3d就能训练？

**Comment by flymin** [comment]
No, bevfusion actually expose the mmdet3d package for you. I know it is strange but this is their design.

Installing mmdet3d from third-party/bevfusion should be fine, no matter develop mode or not.

**Comment by flymin** [comment]
Let me explain more.

NuScenesTDataset is located in our code rather than mmdet3d. Since it successfully located the class definition, I think mmdet or mmcv should be fine. However, it seems to read a wrong class definition, which I cannot understand. One reason I can think of is name duplication, but I do not think there is a class named NuScenesTDataset other than this project.

**Comment by flymin** [comment]
Any update on this? Have you solved this issue?

**Comment by wang-kangkang** [comment]
> Any update on this? Have you solved this issue?

I went through the code and clearly saw that the code for mmdet3d in the site-packages I installed had been modified, losing the last parameter 'force_all_boxes', but I did not make any changes to the code. I haven't figured out why either. I think one possible reason is the different installation command. In the MagicDrive image model, the installation command for bevfusion is "pip vvv install ." In the MagicDrive video model, the installation command for bevfusion is "pip install -e ." Can you check if changing the installation command line works

**Comment by flymin** [comment]
`-e` stands for editing mode, which allows you to edit the source code (i.e., `third-party/bevfusion/mmdet3d`) after installation. On the contrary, any edition in the source code will not take effect if you install the package without `-e` (code under `site-packages` will be a standalone copy for the installation).
