### ISSUE TITLE
about xformers and triton

### ISSUE THREAD

**Issue by wang-kangkang** [cure-lab/MagicDrive#125]
I will ask myself and answer myself.
My environment has been successfully installed. i find the keypoint.

the right environment raise a log:
[2024-12-09 01:29:58,942][xformers][WARNING] - A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
and this environment can training.

if you install triton, it will be raise bug and stop training:
    from ..._flash_attn.flash_attn_triton import (
ModuleNotFoundError: No module named 'xformers._flash_attn'

**Comment by flymin** [comment]
Thank you. I have updated the doc for it.
