### ISSUE TITLE
A issue about 12HZ data generation

### ISSUE THREAD

**Issue by Miayui** [cure-lab/MagicDrive#126]
When I tried to run `bash scripts/ann_generator.sh 12 --ann_strategy 'interp'`, the terminal show 
```
...
total samples in val: 6019 
...
```
After that, i tried to run `python tools/create_data.py nuscenes --root-path ../data/nuscenes --out-dir ../data/nuscenes_mmdet3d-12Hz --extra-tag nuscenes_interp_12Hz --max-sweeps -1 --version interp_12Hz_trainval`, the terminal show
```
...
total scene num: 850
exist scene num: 150
train scene: 0, val scene: 150
...
```
I think it means the 12HZ data generation only generate val dataset.
Though I already know you have released all the pre-generated annotations, i still hope you could share the method for generation 12HZ train dataset, since i might use my own dataset later.
Thank you so much for your great work! Looking forward to your reply!

**Comment by flymin** [comment]
You can find the related code [here](https://github.com/JeffWang987/ASAP/blob/52316629f2a87ef2ef5bbc634d33e9544b5e39a7/sAP3D/nusc_annotation_generator.py#L101). I remember that ASAP indeed only contains the val. set by default, and manual changes have to be made in their code.

I will try to search for my old materials in the following days. In the meantime, I hope the information above helps you.

**Comment by Miayui** [comment]
Thank you for your help, it's useful to me! According to your prompt:

- I deleted all the error files that were generated earlier(it seems important, otherwise, the following changes cannot take effect)
- I tried to change the related code to :

```
-----origin-------
val_scene_ids = splits['val']
-------------------
----change_to----
scene_ids = splits['train']
val_scene_ids = splits['val']
scene_ids.extend(val_scene_ids)
------------------
------------------
other 'val_scene_ids' change to 'scene_ids'
``` 

- run `bash scripts/ann_generator.sh 12 --ann_strategy 'interp'`
- run `python tools/create_data.py nuscenes --root-path ../data/nuscenes --out-dir ../data/nuscenes_mmdet3d-12Hz --extra-tag nuscenes_interp_12Hz --max-sweeps -1 --version interp_12Hz_trainval` and the terminal show:
```
...
total scene num: 850
exist scene num: 850
train scene: 700, val scene: 150
...
```
**It works! Thank you for your help again!**

**Comment by flymin** [comment]
Glad to hear that!
