### ISSUE TITLE
About DataSets

### ISSUE THREAD

**Issue by Moongod-Love** [cure-lab/MagicDrive#131]
![image](https://github.com/user-attachments/assets/61dbfd2a-7376-4245-aa3f-6e9ce8049551)
I want to know if I can complete the entire process using only v1 mini, and whether I need to download the complete trainval dataset or just metadata.  
Thank you!

**Comment by flymin** [comment]
Duplicate #9, #117

**Comment by Moongod-Love** [comment]
Thanks.  It helps me a lot.
