### ISSUE TITLE
Save the generated image to a size of 1600 * 900

### ISSUE THREAD

**Issue by LeonisAlpha** [cure-lab/MagicDrive#16]
> Yes, we kept the original data processing pipeline. Actually, we upscale and pad each generated images to 1600x900 and save them to disk, so that we can run the original code without any change.

Thanks for your reply!

May I ask if you could explain the specific operation of pads and upsamples here?

**Comment by flymin** [comment]
Please check the downsample pipeline. 

Basically, it first downsamples w and h with a fixed ratio, then crops one side (top if I am correct). Therefore, to upsample, we first interpolate w and h with a fixed ratio, then pad top to the original size. Upsample should use bicubic interpolation.
