### ISSUE TITLE
Weights of generate video

### ISSUE THREAD

**Issue by weizhou1991** [cure-lab/MagicDrive#20]
Hi, 
Thank you so much for you wonderful work, I got a simple question, does the weights you post used for image generation same with the video generation's ? I saw you post the training process of video gen, however, nusence dataset is kind of huge, it take times, so I am wondering if I could just use your weights to test the effect of video generation. I really appreciate your help ! 

Best,

**Comment by flymin** [comment]
Sorry, I cannot release the weight soon, but all the resources are released. You can train your own. I will close this issue for now, and will let you know if it is possible.
