### ISSUE TITLE
camera pose coding and change camera intrinsic/extrinsic to generate images

### ISSUE THREAD

**Issue by imbinwang** [cure-lab/MagicDrive#21]
Thanks for sharing this work. As the section 4.1 of your paper shows, the camera parameters are encoded by Fourier embedding and a MLP. By this way, could we slightly change camera intrinsic/extrinsic to generate images? I didn't see any results in your paper about camera control.

**Comment by flymin** [comment]
That’s a good question and currently the controllability of camera pose is not very accurate due to the lack of diverse training data. You can check the discussion [here](https://openreview.net/forum?id=sBQwvucduK&noteId=1Sjlo9RPiz) and Appendix J for some exploration.

**Comment by imbinwang** [comment]
Appendix J shows the camera fov cloud be edited. Thanks for clarification.

**Comment by imbinwang** [comment]
Another question: could the car be turned upside down to generate an accident scene by changing the orientation of the control box? The paper demonstrate the car can be rotated from head to tail. The nuscenes dataset also lacks such training cases.

**Comment by flymin** [comment]
I suppose not, because there are no such cases during training.

**Comment by imbinwang** [comment]
Get it. Thank you.
