### ISSUE TITLE
torch version and xformers install

### ISSUE THREAD

**Issue by Leedonus** [cure-lab/MagicDrive#24]
Thanks for sharing this work! I would like to ask if the torch version needs to be 1.12.0+ when training, since xformer relies on 1.12.0+. However, torch version in README is 1.10.2. 
![2](https://github.com/cure-lab/MagicDrive/assets/58412102/e319935d-d2f5-403a-a67d-2d75baa109da)

**Comment by flymin** [comment]
No, as said in our [doc](https://github.com/cure-lab/MagicDrive/blob/main/doc/xformers.md), we used torch 1.10.2.

BTW, if you have problems with xformers, please ignore the package. It is totally optional as said in the readme.
