### ISSUE TITLE
Some questions about model training

### ISSUE THREAD

**Issue by 24werewolf** [cure-lab/MagicDrive#25]
I followed the training script and the format of the training model obtained is as follows.
<img width="361" alt="屏幕快照 2024-04-01 下午4 37 11" src="https://github.com/cure-lab/MagicDrive/assets/20612761/c8a641a9-c2a7-4ce9-8fc0-b870a1692407">

However, the format of the officially provided pre-training weights is
<img width="352" alt="屏幕快照 2024-04-01 下午4 37 37" src="https://github.com/cure-lab/MagicDrive/assets/20612761/cdfae671-075d-4099-91c5-2883305667a5">

**Comment by flymin** [comment]
Your first figure shows the checkpoint for diffusers to resume. However, the model-to-load is saved at the end of training by default. Please configure the interval for model saving if needed.
