### ISSUE TITLE
where can I find forked version of mmdet3d required by the video branch?

### ISSUE THREAD

**Issue by weimzh** [cure-lab/MagicDrive#26]
Hi,

the README.md file in video branch contains this:
```
Datasets

Please prepare the nuScenes dataset as [bevfusion's instructions](https://github.com/mit-han-lab/bevfusion#data-preparation). 

Note:
Run with our forked version of mmdet3d.
```

however I don't know where I can find that forked version of mmdet3d.  Could the URL be added in the file?

I'm asking this because I'm getting weird exceptions when using the official version of mmdetction3d to generate the .json files required by scripts/ann_generator.sh in ASAP.  Not sure if not using the forked version is the problem.

Thanks in advance.

**Comment by flymin** [comment]
It is well-located in [this repo](https://github.com/cure-lab/MagicDrive/tree/video/third_party/bevfusion).

You must have skipped some steps in our readme. As we said, please go through the image generation and understand the code structure before starting video generation. Thanks.

**Comment by weimzh** [comment]
thanks for answer

If I follow the exact step as in README this step currently fails:

```
Please follow [ASAP](https://github.com/JeffWang987/ASAP/blob/main/docs/prepare_data.md) to generate interp annotations for nuScenes. Simply, the following command should do the work:

# in ASAP root.
bash scripts/ann_generator.sh 12 --ann_strategy 'interp'
```

```
# bash scripts/ann_generator.sh 12 --ann_strategy 'interp' 
Traceback (most recent call last):
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/disk1/ASAP/sAP3D/nusc_annotation_generator.py", line 357, in <module>
    nusc_20Hz_rst = mmcv.load(opts.lidar_inf_rst_path)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/fileio/io.py", line 64, in load
    with StringIO(file_client.get_text(file)) as f:
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1027, in get_text
    return self.client.get_text(filepath, encoding)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 552, in get_text
    with open(filepath, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: './out/lidar_20Hz/results_nusc.json'
loading nuscenes dataset...
loading 20Hz LiDAR inference results...
```

as the exception indicated the results_nusc.json file is missing.  However I'm also not able to generate it by following the 'advanced method' [here](https://github.com/JeffWang987/ASAP/blob/main/docs/prepare_data.md) with the code in third_party/bevfusion as several dependencies used by test.py seems missing.

should I generate it with official mmdetection3d?  not sure what's the proper way to do so.

thanks again.

**Comment by flymin** [comment]
Are you trying to run ASAP with our environment? I don't think it will work.

It would be better to run their code in another environment as described in their repo. And if you have any problem related to ASAP, please ask the ASAP team. Our code does not depend on their code or model.
