### ISSUE TITLE
Conditioning on Segmentation Maps

### ISSUE THREAD

**Issue by samueleruffino99** [cure-lab/MagicDrive#28]
Hello, great work!

I was wondering whether you thougth about conditioning on the image segmentation maps (generated with some algorithm on NuScenes images).
Because I am not quite sure, I would expect segmentation maps have more information about the shapes of the scene/objects compared to 3d bboxes + class, but maybe it is not the case if you already considering and discraded it.

Thank you!!

**Comment by flymin** [comment]
It is possible and you can search for many excellent works on that application. Since segmentation maps are 2D, for instance, controlnet can already support this. In this paper, we only consider 3D controls. Thanks.
