### ISSUE TITLE
Can use nuscenes mini to train？

### ISSUE THREAD

**Issue by yancx8** [cure-lab/MagicDrive#29]
Thank you for your good job!!
I tried to use nusenes mini to run a training demo, but raise error "No such file or directory: 'data/nuscenes/maps/expansion/singapore-onenorth.json', so i wonder if this version can only train on full nuscenes dataset?
"

**Comment by zhangxiao696** [comment]
you should download Map expansion in https://www.nuscenes.org/nuscenes， and put them in maps folder.

**Comment by zhangxiao696** [comment]
It is compatible with Pytorch==1.10.2, just follow the steps of the author.
`cd ${floder of xformers}; pip -vvv install .`

**Comment by yancx8** [comment]
Thank you. I have trird to `cd ${floder of xformers}; pip -vvv install .`
but raise error "No such file or directory: '/code/third_party/xformers/xformers/version.py', i didn't find the version.py, have you meet the same problem?

**Comment by yancx8** [comment]
I have solve the problem. Before installing xformer, you should `cd /root/miniconda3/envs/magicdrive/lib/python3.8/subprocess.py`, line425, change check=True to check=False.

But wneh i train with nuscenes mini, raise error:packaging.version.InvalidVersion: Invalid version: '0.0.19+.d20240506'

**Comment by flymin** [comment]
Definitely, it is because you are downloading the zip rather than cloning this project repo.

Please check #8.
