### ISSUE TITLE
question about view consistentence

### ISSUE THREAD

**Issue by haofengsiji** [cure-lab/MagicDrive#3]
Does the term "hidden state of neighbor" refer to the latent representation of the neighboring image or the scene-level encoding embedding?
Additionally, when addressing view consistency, does the model output multiple-view results simultaneously or only one view?

**Comment by flymin** [comment]
1. it means "the latent representation of the neighboring image"
2. multi-view images are generated simultaneously. The model parameters are shared for different views.
