### ISSUE TITLE
any idea about improve consistency and continuity for front-rear frames on video branch?

### ISSUE THREAD

**Issue by zhangxiao696** [cure-lab/MagicDrive#30]
hello,  I'm here to ask for your advice again. 
I found that  the effect is relatively poor in consistency and continuity of front-rear frames when I generate a video. Do you have any suggestions regarding this problem？

**Comment by kila9112** [comment]
Hello, i try to generate a video. When i follow the command `bash scripts/ann_generator.sh 12 --ann_strategy 'interp'`, am error raised: No such file or directory: './out/lidar_20Hz/results_nusc.json'. Can you tell me how to get the file:results_nusc.json'?Thank you very much!!

**Comment by flymin** [comment]
> hello, I'm here to ask for your advice again. I found that the effect is relatively poor in consistency and continuity of front-rear frames when I generate a video. Do you have any suggestions regarding this problem？

From my perspective, I do not think it is a problem. Since there is no overlap between the front view and the rear view, it does not make sense to make them "consistent".
