### ISSUE TITLE
[unet-controlnet-question] Is the `ControlnetUnetWrapper` necessary?

### ISSUE THREAD

**Issue by kandrio** [cure-lab/MagicDrive#34]
Good afternoon!

Is the `ControlnetUnetWrapper` object necessary [here](https://github.com/cure-lab/MagicDrive/blob/920b7073ed1ebce8f265b67f51cb35693de954da/magicdrive/runner/multiview_runner.py#L175)?

The `self.unet` weights are supposed to be already copied into the `self.controlnet`, [here](https://github.com/cure-lab/MagicDrive/blob/920b7073ed1ebce8f265b67f51cb35693de954da/magicdrive/runner/multiview_runner.py#L119). 

Therefore, why initialize a `ControlnetUnetWrapper` object, since you already have everything under `self.controlnet`?

Thank you, in advance

**Comment by flymin** [comment]
In some cases, you need to make only one single `nn.Module` for the whole project. Otherwise (also in case you do not know why you need it), it is useless.
