### ISSUE TITLE
How could i change the prompt(text) via interactive_gui.py

### ISSUE THREAD

**Issue by cam-ai** [cure-lab/MagicDrive#37]
ex, i config the prompt with ['sunny', 'rainy']

**Comment by flymin** [comment]
Please check the latest commit on the main branch. I just added the functionality.
Original:
![original](https://github.com/cure-lab/MagicDrive/assets/28671430/9c77631c-1dbb-4f72-99b8-df2618753304)

For night:
![night](https://github.com/cure-lab/MagicDrive/assets/28671430/185918e7-c3d4-4f5e-b425-539f1fff7d76)

For rain:
![rain](https://github.com/cure-lab/MagicDrive/assets/28671430/fd36c8bd-2472-4a5a-a934-68f2a9da5a22)

Enjoy!

**Comment by cam-ai** [comment]
Nice! Great Job!
