### ISSUE TITLE
About video quality

### ISSUE THREAD

**Issue by PointsCoder** [cure-lab/MagicDrive#38]
Dear authors,

Thanks for your great work!

I have a question regarding the quality of the generated video. I loaded the pretrained video unet and got videos like this:
![1_16_gen0-ezgif com-video-to-gif-converter](https://github.com/cure-lab/MagicDrive/assets/28640612/7dcbf849-03e7-45a0-b09f-37d92806d94e)
It seems to have some artifacts in the video and some views are more blurry than others. 

I am wondering if this is a normal phenomenon or if I did something wrong.

Thanks!

**Comment by flymin** [comment]
It is acceptable for this case. There are many pedestrians in the scene, and our model cannot generate them very well.
