### ISSUE TITLE
The inputs of view-conditioned generation.

### ISSUE THREAD

**Issue by Little-Podi** [cure-lab/MagicDrive#4]
Hi, congrats for your excellent work! I have a question regarding view-conditioned generation in Fig. 6:
![fig6](https://github.com/cure-lab/MagicDrive/assets/96873712/fc1daad1-7c3a-42b5-9c51-b58a88b20c7f)
I am wondering how the condition view image is provided to the denoising process. Is it generated by DDIM inversion?

**Comment by flymin** [comment]
Yes, we use DDIM inversion.

**Comment by Little-Podi** [comment]
I see. Then, what is the diffusion model used to conduct the inversion? From my understanding, if the single-image diffusion model is used, it cannot faithfully reproduce the conditional view, as the final DDIM sampling is processed by the multi-view diffusion model. Am I right?

**Comment by flymin** [comment]
Sorry, I made a mistake in the last reply. We did not use DDIM inversion. We
1. add the sampled noise to the given view according to the scheduler and use it as the input for noise prediction;
2. replace the predicted noise with ground truth for the given view.

similar to the inpainting process.

**Comment by Little-Podi** [comment]
Sounds effective. Thanks for your detailed reply.
