### ISSUE TITLE
About Todo list updates

### ISSUE THREAD

**Issue by KevenLee** [cure-lab/MagicDrive#40]
I have observed two pending tasks on your to-do list that align with my interests. May I inquire if it would be convenient for you to share the associated configurations, weightings, and the code at this time?
 

> - [ ] config and pretrained weight for high resolution
> - [ ]  train and test code for CVT and BEVFusion

**Comment by flymin** [comment]
Currently, we are primarily focusing on the development of video generation and subsequent tasks, so these to-dos will be released later. For downstream perceptual tasks, we will release part of the bevformer code used for video generation evaluations in this week for the W-CODA2024 challenge. You can refer to the progress of the challenge in the meantime.

**Comment by flymin** [comment]
All checkpoints released!
