### ISSUE TITLE
How to generate videos in MagicDrive-t using pretrained models.

### ISSUE THREAD

**Issue by LeningWang** [cure-lab/MagicDrive#43]
I would like to directly obtain visualizations in MagicDrive-t using pretrained weights for rawbox_mv2.0t_0.4.3.yaml on OneDrive. Could you please provide specific execution scripts, preferably for generating frames at different time intervals? Thank you very much.

**Comment by LeningWang** [comment]
We used the following script to visualize based on the provided model files, but the generated video is completely black.

![d4aad6a0f4f5f51bba2c0358d14a9d9](https://github.com/cure-lab/MagicDrive/assets/74409418/3af62f87-48b8-41a8-ad8d-cfaa073ba738)

**Comment by flymin** [comment]
Your `ann_file` for testing is wrong.

We have updated the readme for the link to all pre-generated data files. Could you try again?

**Comment by flymin** [comment]
Sorry, I forgot to update some code.

It is a known issue that overflow would happen when `xformers` is disabled. Could you pull the latest commit and try again?

**Comment by LeningWang** [comment]
Maybe if we don't use xformers, we won't need to pull the latest commit? In other words, we only download nuscenes_mmdet3d-12Hz/nuscenes_interp_12Hz_infos_val.pkl and run python tools/test.py resume_from_checkpoint=${RUN_LOG_DIR} task_id=${ANY} runner.validation_times=4 runner.pipeline_param.init_noise=rand_all ++dataset.data.val.ann_file=${ROOT}/../data/nuscenes_mmdet3d-12Hz/nuscenes_interp_12Hz_infos_val.pkl

**Comment by flymin** [comment]
I do not understand why you refuse to take updates.

Anyway, you are free to choose to use or not to use xformers with a6b0d8d. Without it, please always enable xformers.

**Comment by LeningWang** [comment]
Thanks, my problems are well solved. Thank you, nice person, and nice work.

**Comment by facethewindha** [comment]
> 谢谢，我的问题已经解决了。谢谢你，好人，干得好。

你好我想咨询一下，我直接下载video分支然后配置预训练权重数据集和环境可以运行吗，跟main分支没关系吗
