### ISSUE TITLE
Can the generated video improve MOT proformence

### ISSUE THREAD

**Issue by cam-ai** [cure-lab/MagicDrive#44]
I saw in your paper, you said the generated image could improve 3D object detection task KPI, I checked your generated video, the generated car or other object, the consistency is not very well in image sequence, So I want to know, does the un-consistency issue  decrease some MOT KPI if i use these generated video to enhance training dataset.

**Comment by flymin** [comment]
We haven't tried that yet, but we welcome any further improvements or reports.

**Comment by cam-ai** [comment]
Thanks for your reply.

**Comment by flymin** [comment]
FYI, our another work focusing on controllable video generation have tried to apply generated data for MOT training. You may want to take a look: 

TrackDiffusion: Tracklet-Conditioned Video Generation via Diffusion Models
https://arxiv.org/abs/2312.00651
https://github.com/pixeli99/TrackDiffusion

**Comment by cam-ai** [comment]
Thanks.
