### ISSUE TITLE
How to run the codebase with higher cuda version

### ISSUE THREAD

**Issue by SecretMG** [cure-lab/MagicDrive#45]
Thank you for your excellent work. I have noticed that the codebase relies on multiple specific versions of the mm series code repository, and the highest graphics card computing power supported by pytorch-cuda10.2 is sm_70. Although V100 can be used, many new versions of graphics cards such as A series or L40S series cannot support sm_70. Is it possible for us to make the code run on these graphics cards?

**Comment by flymin** [comment]
A series can use this codebase and we have tested it. Please see [FAQ](https://github.com/cure-lab/MagicDrive/blob/main/doc/FAQ.md#q2-how-to-setup-on-ampere-gpus-eg-a100-a800)
