### ISSUE TITLE
No module named 'xformers._flash_attn'

### ISSUE THREAD

**Issue by haichen-ber** [cure-lab/MagicDrive#47]
Hello, thanks for your excellent work, I am getting an error ""No module named 'xformers._flash_attn'"" when I run the demo command you gave.
Environment:
CUDA10.2
PyTorch 1.10.2
gcc 7.4.0
NVIDIA A100

**Comment by haichen-ber** [comment]
> I am not sure about the reason. Could you try https://github.com/cure-lab/MagicDrive/tree/disable-flash and reinstall the xformers? If not solved, please provide more trace.

I've tried that and it still reports the same error. More detailed error reporting is:
![531bf090bab9d885698287d3d2d6d93](https://github.com/cure-lab/MagicDrive/assets/54704588/eacbc53a-d645-4ef2-a450-31986bf79454)
![531bf090bab9d885698287d3d2d6d93](https://github.com/cure-lab/MagicDrive/assets/54704588/eacbc53a-d645-4ef2-a450-31986bf79454)
![531bf090bab9d885698287d3d2d6d93](https://github.com/cure-lab/MagicDrive/assets/54704588/eacbc53a-d645-4ef2-a450-31986bf79454)
![Uploading 531bf090bab9d885698287d3d2d6d93.png…]()

**Comment by haichen-ber** [comment]
> I am not sure about the reason. Could you try https://github.com/cure-lab/MagicDrive/tree/disable-flash and reinstall the xformers? If not solved, please provide more trace.

I've tried that and it still reports the same error. More detailed error reporting is:
![531bf090bab9d885698287d3d2d6d93](https://github.com/cure-lab/MagicDrive/assets/54704588/da1c44b6-97da-4e65-a8e8-ef2cbe87e000)

**Comment by flymin** [comment]
Did you install triton? Can you remove it and try?

**Comment by haichen-ber** [comment]
> Did you install triton? Can you remove it and try?

I tried it and it still reports the same error. I even switched to a different version of triton.

**Comment by flymin** [comment]
Let me explain. 

We never installed triton and the environment without it should be fine. I think you may need to remove triton and rebuild xformers again. However, for a quick workaround, please try to add `XFORMERS_FORCE_DISABLE_TRITON=1` to your env. Anywhy, [this function](https://github.com/cure-lab/MagicDrive/blob/a6062d05f9d2c73d8259a96a5f86d150c60808aa/third_party/xformers/xformers/__init__.py#L41) should return `False`. You may take a closer look.

**Comment by haichen-ber** [comment]
> Let me explain.
> 
> We never installed triton and the environment without it should be fine. I think you may need to remove triton and rebuild xformers again. However, for a quick workaround, please try to add `XFORMERS_FORCE_DISABLE_TRITON=1` to your env. Anyway, [this function](https://github.com/cure-lab/MagicDrive/blob/a6062d05f9d2c73d8259a96a5f86d150c60808aa/third_party/xformers/xformers/__init__.py#L41) should return `False`. You may take a closer look.

Ok, I re-downloaded xformers based on your comments, but I get the following error:
![b7bb506b66e86799d92e92b8c285ea3](https://github.com/cure-lab/MagicDrive/assets/54704588/7996ef12-2e25-4fd3-a06f-3aa8ea3e96f6)

**Comment by haichen-ber** [comment]
> Let me explain.
> 
> We never installed triton and the environment without it should be fine. I think you may need to remove triton and rebuild xformers again. However, for a quick workaround, please try to add `XFORMERS_FORCE_DISABLE_TRITON=1` to your env. Anyway, [this function](https://github.com/cure-lab/MagicDrive/blob/a6062d05f9d2c73d8259a96a5f86d150c60808aa/third_party/xformers/xformers/__init__.py#L41) should return `False`. You may take a closer look.

Ok, I re-downloaded xformers based on your comments, but I get the following error:
![Uploading 24af7786a1ce6d5741a1d53f17813e0.png…]()

**Comment by flymin** [comment]
Your figure is not working. BTW, please make sure you install xformers in this repo.

**Comment by haichen-ber** [comment]
> Your figure is not working. BTW, please make sure you install xformers in this repo.

I'm sure I downloaded xformers from this repo, but it really doesn't work for me.

**Comment by haichen-ber** [comment]
> Your figure is not working. BTW, please make sure you install xformers in this repo.

I'm sure I downloaded xformers from this repo, but it really doesn't work for me.
![24af7786a1ce6d5741a1d53f17813e0](https://github.com/cure-lab/MagicDrive/assets/54704588/30475a1d-b975-4284-be5d-c28eae3f790f)

**Comment by flymin** [comment]
Ok, now it is clearly another problem. 

Did you download and prepare all the pre-trained weights as described in the readme? By default, nothing would be downloaded automatically.

BTW, although it is not related to your problem above, I note that you are using A100 with CUDA10.2, which is not compatible. We have docs for the A-series card.

**Comment by haichen-ber** [comment]
> Ok, now it is clearly another problem.
> 
> Did you download and prepare all the pre-trained weights as described in the readme? By default, nothing would be downloaded automatically.
> 
> BTW, although it is not related to your problem above, I note that you are using A100 with CUDA10.2, which is not compatible. We have docs for the A-series card.



> Ok, now it is clearly another problem.
> 
> Did you download and prepare all the pre-trained weights as described in the readme? By default, nothing would be downloaded automatically.
> 
> BTW, although it is not related to your problem above, I note that you are using A100 with CUDA10.2, which is not compatible. We have docs for the A-series card.

Thanks, it's solved！！！！！！！！！！！！！！！！！

**Comment by Michael-Yi-Rong** [comment]
> Let me explain.
> 
> We never installed triton and the environment without it should be fine. I think you may need to remove triton and rebuild xformers again. However, for a quick workaround, please try to add `XFORMERS_FORCE_DISABLE_TRITON=1` to your env. Anyway, [this function](https://github.com/cure-lab/MagicDrive/blob/a6062d05f9d2c73d8259a96a5f86d150c60808aa/third_party/xformers/xformers/__init__.py#L41) should return `False`. You may take a closer look.

MY HERO!
