### ISSUE TITLE
When will open the training code? Thanks

### ISSUE THREAD

**Issue by 24werewolf** [cure-lab/MagicDrive#5]

**Comment by flymin** [comment]
We are still preparing that. Will release ASAP.

**Comment by 24werewolf** [comment]
> We are still preparing that. Will release ASAP.

cool

**Comment by jongchyisu** [comment]
Any updates on code release?

**Comment by 24werewolf** [comment]
Everyone is looking forward to the training code being open source

**Comment by flymin** [comment]
Updated. Please check.

Cheers!
