### ISSUE TITLE
xformers running error: NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs

### ISSUE THREAD

**Issue by SecretMG** [cure-lab/MagicDrive#50]
I am sorry to bother you, but I am getting the following error when I try to train the video generation model after successfully installing xformers from the repo. I followed the [installation instructions of A series](https://github.com/cure-lab/MagicDrive/blob/main/doc/FAQ.md#q2-how-to-setup-on-ampere-gpus-eg-a100-a800) strictly. Thus I can run the program successfully with xformers disabled.

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40

Thank you for your consistently helpful responses.

**Comment by SecretMG** [comment]
I have solved the issue. The problem occurred because I didn't set the correct CUDA_HOME and other environment variables before installing xformers.

**Comment by wang-kangkang** [comment]
> I have solved the issue. The problem occurred because I didn't set the correct CUDA_HOME and other environment variables before installing xformers.

I also encountered the same problem as you, which environment variables did you change
