### ISSUE TITLE
About downloading .pkl file of dataset

### ISSUE THREAD

**Issue by pkudba** [cure-lab/MagicDrive#51]
Excuse me, in the section of 'Prepare Data', you say that
"You can download the .pkl files from OneDrive. They should be enough for training and testing."
However, the OneDrive link does not work. Could you please provide a valid dataset link of the NuScenes dataset similar to bevfusion's instruction?

**Comment by flymin** [comment]
Sorry, I have fixed it. 
In case you find other broken links, please do not hesitate to let me know.

**Comment by chenjincj03** [comment]
Excuse me , the link of OneDrive for alumni is terminated from 16 Dec 2025. Could you please provide a new dataset link.

**Comment by flymin** [comment]
Please see #172
