### ISSUE TITLE
Bug in nuscenes_t_dataset

### ISSUE THREAD

**Issue by ziyanGao** [cure-lab/MagicDrive#53]
There is a syntax error in the build_clips function on line 59 of the nuscenes_t_dataset.py file in the video branch of the current repository. The line currently reads:
len(scene[start] >= 33)
It should probably be:
len(scene[start]) >= 33
Please investigate and correct this issue. Thank you!

**Comment by flymin** [comment]
Thank you for the issue. I have fixed it.
