### ISSUE TITLE
What's the meaning of several parametes in default.yaml?

### ISSUE THREAD

**Issue by yancx8** [cure-lab/MagicDrive#55]
foreground_loss_weight: 0
bbox_drop_ratio: 0
bbox_add_ratio: 0
bbox_add_num: 3

I find the bboxs cannot completely cover the target, if i change the parameters above,can it be improved?
Thank you very much!

**Comment by flymin** [comment]
FYI:
- `foreground_loss_weight`: Not implemented/tested, cr GeoDiffusion (https://arxiv.org/abs/2306.04607)
- `bbox_drop_ratio`: random ratio to drop visible boxes on each view
- `bbox_add_ratio`: random ratio to add invisible boxes on each view
- `bbox_add_num`: number to add invisible boxes, work with `bbox_add_ratio`

For more information about visibility, please refer to Appendix A of our paper.

[Here](https://github.com/cure-lab/MagicDrive/blob/84cb4e338b192203a4bda630c748302c91e9473a/configs/exp/224x400.yaml#L13) in our model, we randomly add unseen bboxes for augmentation. However, dropping may not help. You may try different parameters in your case.
