### ISSUE TITLE
How to use the pretrained weight "SDv1.5mv-rawbox_2023-09-07_18-39_224x400" to launch another train?

### ISSUE THREAD

**Issue by kila9112** [cure-lab/MagicDrive#56]
Thank you for your work!
I want to train my data with the pretrained weight "SDv1.5mv-rawbox_2023-09-07_18-39_224x400",but lose "pytorch_model.bin". 
And if i train the model with my own "pytorch_model.bin", it raised error "pytorchstreamreader failed reading zip archive: failed finding central direc".
How can i train with a pretrained weight?
Thank you very much!

**Comment by flymin** [comment]
Please refer to the video branch, which loads image generation for video generation training.

For your problem, it seems like a pytorch env problem or error in the downloaded file. Please make sure you can run the inference before you start.

**Comment by kila9112** [comment]
Thank you for your suggention.
I find another resolution of 272×736 is also supported, how can i change the code?

**Comment by flymin** [comment]
Yes, we do not include the implementation here. You can change the resolution through config, but you have to change the code for BEV map encoder, to have the same embedding size as the image latent (similar logic as ControlNet). Other parts should be fine.
