### ISSUE TITLE
Adding objects

### ISSUE THREAD

**Issue by mrabiabrn** [cure-lab/MagicDrive#57]
Hi,

Thank you for this excellent work. 

I noticed that it's possible to add more cars to the scene when I checked your project page. Could you please indicate the relevant part of the repository?

**Comment by flymin** [comment]
Yes, it is possible if you prepare feasible coordinates for boxes. We did not include this part in current code. Considering all boxes from the datasets are feasible, we only tried to delete/change some of them. Deletion and addition share the same logic and functionality to our model.
