### ISSUE TITLE
version of some packpages

### ISSUE THREAD

**Issue by ZhiyingDu** [cure-lab/MagicDrive#58]
Could you tell me the version of mmcv, mmdet, mmsegmentation please?

**Comment by flymin** [comment]
Please find them [here](https://github.com/cure-lab/MagicDrive/tree/main/requirements).

**Comment by ZhiyingDu** [comment]
Get it, thanks!

**Comment by ZhiyingDu** [comment]
> Please find them [here](https://github.com/cure-lab/MagicDrive/tree/main/requirements).

Git it, thanks!
