### ISSUE TITLE
Detection Results using BEVFusion of Table I?

### ISSUE THREAD

**Issue by colian** [cure-lab/MagicDrive#6]
Hi, nice work!

Do the results of Table I  all use the checkpoint officially released by bevfusion? Or the checkpoint is trained by urself?

Looking forward to your reply.

**Comment by flymin** [comment]
In Table 1, we use all perception models only for testing. Therefore, we adopt the officially released ckpts without training.

**Comment by colian** [comment]
Thanks for your reply!

Since the officially released ckpt of BEVFusion is in resolution of 256*704, and you resized the synthesis image into 256*704 resolution for evaluation?

**Comment by flymin** [comment]
Yes, we kept the original data processing pipeline. Actually, we upscale and pad each generated images to 1600x900 and save them to disk, so that we can run the original code without any change.

**Comment by colian** [comment]
Thanks for your quick reply!

**Comment by LeonisAlpha** [comment]
> Yes, we kept the original data processing pipeline. Actually, we upscale and pad each generated images to 1600x900 and save them to disk, so that we can run the original code without any change.

Thanks for your reply!

May I ask if you could explain the specific operation of pads and upsamples here?

**Comment by zhaoyangwei123** [comment]
> Hi, nice work!
> 
> Do the results of Table I all use the checkpoint officially released by bevfusion? Or the checkpoint is trained by urself?
> 
> Looking forward to your reply.

May I ask how you generate a new test set to inference BEVfusion?
