### ISSUE TITLE
Machine and time query request

### ISSUE THREAD

**Issue by ZhiyingDu** [cure-lab/MagicDrive#61]
Hello, I would like to ask you on what machine did you run training for 224x400 with 16 frames with sweeps and generated annotations? And, how long did it take? This is really important to me. Thank you.

**Comment by flymin** [comment]
We used 8*V100 and trained for about 10 days. Although more machines or more gpu memory could help to speed up, we do not enough resources for parameter tuning.

**Comment by WuZhongQing** [comment]
> We used 8*V100 and trained for about 10 days. Although more machines or more gpu memory could help to speed up, we do not enough resources for parameter tuning.

hi，could you please tell me that 8*v100 can use 10 days training 100 epochs ?:
cause we training 100 epochs will takes more than one months.
![image](https://github.com/user-attachments/assets/b85a5d8f-75e6-4b6f-9c36-ec2298e40de3)

and maybe the reason is i don't use h5 file ?
