### ISSUE TITLE
How long train 61 frames?

### ISSUE THREAD

**Issue by yancx8** [cure-lab/MagicDrive#64]
Thank you for your excellent work!
I want to train the 61 frames config with 8 A100, and i have used the map cache. The time of 1 epoch is 15-20 days with 1 batchsize(2 batchsize out of memory), is it normal? How long did you train the 61 frames config? What‘s your batchsize and epoch? Thank you for your answer!

**Comment by flymin** [comment]
We train about 20 days in total for 80k steps. Config is just the one we used. You should have all the hyper-parameters set.

**Comment by yancx8** [comment]
Thank you, i have 15400 steps in one epoch, and i have 8 gpus, it means total step is 15400*8, is it right?

**Comment by flymin** [comment]
No, when counting steps, we do not multiply with the number of processes. The number indicates effective update steps.

**Comment by yancx8** [comment]
![1](https://github.com/user-attachments/assets/f64fd601-71e2-4bd8-8825-8484af842084)
Thank you, i find your batchsize is 1 as well in the config, the picture is my parameters. I also use the advanced_12Hz_infos pkl(download online), but my time is so long in 8 A100 gpus.

**Comment by flymin** [comment]
20-30s/it is fine.
