### ISSUE TITLE
Can 61 frames pretrained weight be released?

### ISSUE THREAD

**Issue by kila9112** [cure-lab/MagicDrive#66]
Thank you for your work!
I find train a 61 frames weight is too long ,can you release a 61 frames weight? Thank you very much!

**Comment by flymin** [comment]
It take time for preparation….

**Comment by yancx8** [comment]
I want to train for 15000 steps for 61 frames, but stopped at step 10000(err occerrd), the checkpoint-10000 folder have be saved, but unet and controlnet folder didn't be saved,  how can i run a test.py only with checkpoint-10000 folder? Or can't run a test.py without unet and controlnet folder?

**Comment by flymin** [comment]
see FAQ

**Comment by flymin** [comment]
Released! see [here](https://github.com/cure-lab/MagicDrive/tree/video?tab=readme-ov-file#magicdrive-t-checkpoints).
