### ISSUE TITLE
Running on local URL:  http://0.0.0.0:7860  To create a public link, set `share=True` in `launch()`.

### ISSUE THREAD

**Issue by Ding2Zhen** [cure-lab/MagicDrive#67]
Please tell me where to modify the share parameter in lauch()
![屏幕截图 2024-07-29 104410](https://github.com/user-attachments/assets/dd680ddd-dbf7-4f41-8507-af95c34780c4)

**Comment by flymin** [comment]
For gradio usage, please refer to the doc or propose issues in [their repo](https://github.com/gradio-app/gradio) to serve your purpose. If you have any questions about our code, please be specific.

**Comment by Ding2Zhen** [comment]
Thanks, revised done
