### ISSUE TITLE
'BasicTransformerBlock' object has no attribute '_args'

### ISSUE THREAD

**Issue by mlsimon734** [cure-lab/MagicDrive#7]
I can't run the full demo or the gradio demo because of the following error:

AttributeError: 'BasicTransformerBlock' object has no attribute '_args'

```python
if crossview_attn_type == "basic":
                    _set_module(self, name, BasicMultiviewTransformerBlock(
                        **mod._args, # Problem line
                        neighboring_view_pair=neighboring_view_pair,
                        neighboring_attn_type=neighboring_attn_type,
                        zero_module_type=zero_module_type,
                    ))
```

I understand that the code is attempting to retrieve the original arguments from the BasicTransformer block, but it seems to be unsuccessful syntactically.

I downloaded an unzipped the pretrained model to /pretrained and have an otherwise functional env.

**Comment by flymin** [comment]
Please install the diffusers located in `third-party`, rather than use the official version.

**Comment by mlsimon734** [comment]
Thanks, that worked. I think FAQ instructions should be updated to include that diffusers should still be installed directly from the `third-party/diffusers` folder rather than from the source.

**Comment by flymin** [comment]
Did you cd to the folder and use ./diffusers or . to install? Do not use `pip install diffusers`.

**Comment by CSUXA** [comment]
thanks,i will try it
