### ISSUE TITLE
Question about initialize class_tokens

### ISSUE THREAD

**Issue by ailearnerkyh** [cure-lab/MagicDrive#70]
When I run the command 
```
python tools/test.py resume_from_checkpoint=${RUN_LOG_DIR} task_id=${ANY} \
	runner.validation_times=4 runner.pipeline_param.init_noise=rand_all \
	++dataset.data.val.ann_file=${ROOT}/../data/nuscenes_mmdet3d-12Hz/nuscenes_interp_12Hz_infos_val.pkl
```
The warning `[ContinuousBBoxWithTextEmbedding] Your class_tokens is not trainable and used without initialization. Please check your training code! ]` occurs. Besides, when I train the code, I can't find `your class_tokens initialized with random` in the INFO, nor can I find `Initializing your class_tokens with text_encoder`.
Is this because I use the checkpoint SDv1.5mv-rawbox_2023-09-07_18-39_224x400, so the class_tokens have no need to be initialized? Looking forward to your reply.

**Comment by flymin** [comment]
If you load a pretrained model with this param, this may occur but it is fine. Otherwise, if you see the warning, please check your code.
