### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by ZhiyingDu** [cure-lab/MagicDrive#71]
Excuse me, i set the batchsize=4, and run this command"scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.4" in A100, it throw a exception when it traind in 25 step, Could you have some suggetions to solve it?
![image](https://github.com/user-attachments/assets/2c3ff34b-c6b8-459b-aa9d-c36f8f549ad4)

**Comment by ZhiyingDu** [comment]
> Excuse me, i set the batchsize=4, and run this command"scripts/dist_train.sh 8 runner=8gpus_t +exp=rawbox_mv2.0t_0.4.4" in A100, it throw a exception when it traind in 25 step, Could you have some suggetions to solve it? ![image](https://private-user-images.githubusercontent.com/111031904/355667403-2c3ff34b-c6b8-459b-aa9d-c36f8f549ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDM0OTEsIm5iZiI6MTcyMzAwMzE5MSwicGF0aCI6Ii8xMTEwMzE5MDQvMzU1NjY3NDAzLTJjM2ZmMzRiLWM2YjgtNDU5Yi1hYTlkLWMzNmY4ZjU0OWFkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMzU5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzYwMmMzNjZiOTFmODdjZGFmMzg5OWRlOGY0N2YxYjdlNGEwNWM0ZWIwNmQzNzhjMmVhMDkzNWNhNGE2OTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SqsJ_qZvqpa5E-ZdsR6YxETJjHTnXhzXy4jJO0CAuiw)

Maybe i can solve this error by set ret_dict['kwargs']['bboxes_3d_data'] to {} if bboxes_3d_data is None, but i'm not sure if this error is indirectly caused by other part of code or if there is something wrong with my data itself. Could you give me some suggestions?  Sincere thanks! 
![image](https://github.com/user-attachments/assets/5a309f04-a345-4481-a09d-c071dd627cdc)

**Comment by flymin** [comment]
You are correct. We should allow `bboxes_3d_data` to be `None`.

**Comment by ZhiyingDu** [comment]
But if i set the `batch_size` to 1, no errors occurred. This is what I am confused about. Why is `bboxes_3d_data` not be `None` when batchsize is set to 1? But when I set `batchsize` to 2 or 4, it will be `None`?

**Comment by flymin** [comment]
It is normal to observe None in very rare cases, but it may happen to some samples. If you have None constantly, there may be something wrong.

**Comment by aipursuing** [comment]
I have met the same problem when I set the batchsize to 4. And when I follow the above method to fix this problem, I will meet the new error `Keyerror: cam_param`, have you met this problem @ZhiyingDu ?

**Comment by flymin** [comment]
Hi @ZhiyingDu @aipursuing 

Could you help me check whether the pr above fixes the issue when bbox is none?

**Comment by ZhiyingDu** [comment]
> Hi @ZhiyingDu @aipursuing
> 
> Could you help me check whether the pr above fixes the issue when bbox is none?

I think it will be fun. I did unconditional initialization and it also works fine after changing. My ugly Code(/doge): 
![image](https://github.com/user-attachments/assets/eb05c81f-10eb-49ee-9688-1c6e9b8b1d7d)

**Comment by aipursuing** [comment]
> Hi @ZhiyingDu @aipursuing
> 
> Could you help me check whether the pr above fixes the issue when bbox is none?

My solution is similar to yours, but I set `bbox_3d_data = {} `instead of `{"cam_params":ret_dict['camera_param']}`. I used your code to run almost 1 hour without any error, so I think there is no problem.

**Comment by flymin** [comment]
@aipursuing Doing so may also solve your issue with `Keyerror: cam_params`. Thank you for your feedback!

@ZhiyingDu I do not think you should allocate parameters here or use the unconditional cam, while null embedding for bboxes should be handled in bbox embedder according to the `mask`. Anyway, `cam_params` is useless in this codebase. Let's not worry about the value of it.
