### ISSUE TITLE
cannot import name 'visualize_camera' from 'mmdet3d.core.utils'

### ISSUE THREAD

**Issue by LJQbiu** [cure-lab/MagicDrive#72]
I’ve tried many versions of mmdet3d, but all of them report an error: cannot import name ‘visualize_camera’ from ‘mmdet3d.core.utils’. Which version of mmdet3d should I use?

**Comment by facethewindha** [comment]
> I’ve tried many versions of mmdet3d, but all of them report an error: cannot import name ‘visualize_camera’ from ‘mmdet3d.core.utils’. Which version of mmdet3d should I use?

Did you solve it? i am same with you now
