### ISSUE TITLE
  File "demo/interactive_gui.py", line 246, in <module>

### ISSUE THREAD

**Issue by WuZhongQing** [cure-lab/MagicDrive#74]
File "demo/interactive_gui.py", line 246, in <module>
    box_id, x_offset, y_offset, z_offset, yaw_offset, box_id, box_viz, box_sel_viz, prompt])
TypeError: __call__() missing 1 required positional argument: 'fn'

i donot known the bugs means what，by the way, i donot change the python file yet。

**Comment by flymin** [comment]
Could it be related to https://github.com/gradio-app/gradio/issues/5729? Otherwise, please paste the full error log here.

**Comment by WuZhongQing** [comment]
> Could it be related to [gradio-app/gradio#5729](https://github.com/gradio-app/gradio/issues/5729)? Otherwise, please paste the full error log here.

感谢老铁， thans a lot

**Comment by WuZhongQing** [comment]
> > Could it be related to [gradio-app/gradio#5729](https://github.com/gradio-app/gradio/issues/5729)? Otherwise, please paste the full error log here.
> 
> 感谢老铁， thans a lo
