### ISSUE TITLE
Hi ,i meet some bug i canot understand: when loading unet(Video)

### ISSUE THREAD

**Issue by WuZhongQing** [cure-lab/MagicDrive#78]
I install all the requirements ,and put all documnts to the right path,but when loading unet from pretrained ckpt, an error appered:
 
![image](https://github.com/user-attachments/assets/46a91daa-52f2-4030-a595-4b5bf9fc5942)

and the error code is:

![image](https://github.com/user-attachments/assets/027033b4-d541-4ff8-b1b5-0692b2039d3d)

could you tell me how to fix it ! By the way, this is a great work!

and this is the structure of my ckpt files:
![image](https://github.com/user-attachments/assets/5a53e874-5ca5-48ca-b3d3-f139dbd21f0c)

**Comment by WuZhongQing** [comment]
> I install all the requirements ,and put all documnts to the right path,but when loading unet from pretrained ckpt, an error appered:
> 
> ![image](https://private-user-images.githubusercontent.com/48616900/360321713-46a91daa-52f2-4030-a595-4b5bf9fc5942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTE4MzgsIm5iZiI6MTcyNDMxMTUzOCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzMjE3MTMtNDZhOTFkYWEtNTJmMi00MDMwLWE1OTUtNGI1YmY5ZmM1OTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDM2ZWUwNmNhNzJjNTkxYzUzZjY1MGQ5N2U5MWQwYzZjZDNhNTY4OWU1YmY1ZjQyMWYwMzQxNTljNDQxOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qCkUdj7kL7zm3H9X9L2tXZpZ0MgxRIeuCxFyr0Pm7hI)
> 
> and the error code is:
> 
> ![image](https://private-user-images.githubusercontent.com/48616900/360321995-027033b4-d541-4ff8-b1b5-0692b2039d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTE4MzgsIm5iZiI6MTcyNDMxMTUzOCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzMjE5OTUtMDI3MDMzYjQtZDU0MS00ZmY4LWIxYjUtMDY5MmIyMDM5ZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNmUyNWY5ZTM4NWJiMTU4Njg0ZDFkMTZlYzczZTMyOTA2ZTE3MmY5Y2UxM2U3MzVjYjdmYTVkZGYyMDlmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7hRSAEGmGJ_4J6Elk7gU3w52zfhgzDunByWVT1Om2Y)
> 
> could you tell me how to fix it ! By the way, this is a great work!

and this is the structure of my ckpt files:
![image](https://github.com/user-attachments/assets/ca431118-708a-4ecd-b46b-7a0790346118)

**Comment by flymin** [comment]
> and this is the structure of my ckpt files: 
> ![image](https://private-user-images.githubusercontent.com/48616900/360336196-5a53e874-5ca5-48ca-b3d3-f139dbd21f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTU1MjgsIm5iZiI6MTcyNDMxNTIyOCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzMzYxOTYtNWE1M2U4NzQtNWNhNS00OGNhLWIzZDMtZjEzOWRiZDIxZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTMyNjYzZWY3NDA5NzY5ZTVkNjJiYmY1MzNlOGVhNmNhYTI5ZDc1YmQ4MmVkNzczYThiZDQzY2E1M2JkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gAkY0zGfhJl6kprfkkfxnja2PV17XRd0UwEB9m-0FUk)

I'm afraid that's not right. Please follow our readme to organize them.

**Comment by WuZhongQing** [comment]
> > and this is the structure of my ckpt files:
> > ![image](https://private-user-images.githubusercontent.com/48616900/360336196-5a53e874-5ca5-48ca-b3d3-f139dbd21f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTU1MjgsIm5iZiI6MTcyNDMxNTIyOCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzMzYxOTYtNWE1M2U4NzQtNWNhNS00OGNhLWIzZDMtZjEzOWRiZDIxZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTMyNjYzZWY3NDA5NzY5ZTVkNjJiYmY1MzNlOGVhNmNhYTI5ZDc1YmQ4MmVkNzczYThiZDQzY2E1M2JkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gAkY0zGfhJl6kprfkkfxnja2PV17XRd0UwEB9m-0FUk)
> 
> I'm afraid that's not right. Please follow our readme to organize them.

thanks for your reply, but you just write about image  generation, could please show your origanization for video generation, thanks a lot ^_^.
![image](https://github.com/user-attachments/assets/f9ce60bb-e42a-4b24-a29a-4b48f771a5fe)

and also , a tried to put those ckpt into magicdrive_t_log,bug that will make other bug .'_'.  .

**Comment by WuZhongQing** [comment]
> > > and this is the structure of my ckpt files:
> > > ![image](https://private-user-images.githubusercontent.com/48616900/360336196-5a53e874-5ca5-48ca-b3d3-f139dbd21f0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTU1MjgsIm5iZiI6MTcyNDMxNTIyOCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzMzYxOTYtNWE1M2U4NzQtNWNhNS00OGNhLWIzZDMtZjEzOWRiZDIxZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTMyNjYzZWY3NDA5NzY5ZTVkNjJiYmY1MzNlOGVhNmNhYTI5ZDc1YmQ4MmVkNzczYThiZDQzY2E1M2JkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gAkY0zGfhJl6kprfkkfxnja2PV17XRd0UwEB9m-0FUk)
> > 
> > 
> > I'm afraid that's not right. Please follow our readme to organize them.
> 
> thanks for your reply, but you just write about image generation, could please show your origanization for video generation, thanks a lot ^_^. ![image](https://private-user-images.githubusercontent.com/48616900/360356233-f9ce60bb-e42a-4b24-a29a-4b48f771a5fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjExODQsIm5iZiI6MTcyNDMyMDg4NCwicGF0aCI6Ii80ODYxNjkwMC8zNjAzNTYyMzMtZjljZTYwYmItZTQyYS00YjI0LWEyOWEtNGI0OGY3NzFhNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MDE2ZjFmNGQ0MmUwYjI0NDNjNGE4YWZkMjMzOTk4MWU1MzMwOWRkNDM2ZGU0NzM0OGVkZTg5ZGQ3NzBmMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tilcCvu0TEtYmDRB3i0Ei035fSihk_05kxY-ORkQDGc)
> 
> and also , a tried to put those ckpt into magicdrive_t_log,bug that will make other bug .'_'. .

my fault，i have areadly done it . thanks !
