### ISSUE TITLE
About experiment

### ISSUE THREAD

**Issue by RYHSmmc** [cure-lab/MagicDrive#79]
Hello, when I replicated your Table 1 experiment with BevFusion using real data, I achieved consistent results with you. However, when we upsampled the 224x400 images to 900x1600 for testing the validation set, the performance AP dropped to 9.1 while your result was 12.3. Could you provide some suggestions?

**Comment by flymin** [comment]
Maybe you can check the interpolation method for up/downsample, which should be BICUBIC. see #16.

**Comment by flymin** [comment]
And also dup with #6.
