### ISSUE TITLE
it occurs error when I install xformers in third_party

### ISSUE THREAD

**Issue by zhangxiao696** [cure-lab/MagicDrive#8]
thanks for your work!

when I install xformers in third_party by using "pip install .", find error:

<img width="892" alt="image" src="https://github.com/cure-lab/MagicDrive/assets/13326803/c476fb6d-d89f-4dcc-b30c-cd86eb0735f3">

if I update code in /opt/conda/lib/python3.7/subprocess.py, xformers is not work:
packaging.version.InvalidVersion: Invalid version: '0.0.19xxx'

<img width="1026" alt="31ff61ed4d89c31f936f15a1ac88562e" src="https://github.com/cure-lab/MagicDrive/assets/13326803/d3b4c1f1-f4b9-4108-8cb5-97a6fa7f99e9">

**Comment by flymin** [comment]
I guess you download the zip rather than clone the repo.

Change [this function](https://github.com/cure-lab/MagicDrive/blob/92a85fac7019df8f3251edbde31a027d058b14da/third_party/xformers/setup.py#L50) to return an empty string (like doing nothing) and re-install xformers. It should fix the error.

**Comment by zhangxiao696** [comment]
> I guess you download the zip rather than clone the repo.
> 
> Change [this function](https://github.com/cure-lab/MagicDrive/blob/92a85fac7019df8f3251edbde31a027d058b14da/third_party/xformers/setup.py#L50) to return an empty string (like doing nothing) and re-install xformers. It should fix the error.

yes, I resolved the problem by using a occupy string. Thanks for your reply.
