### ISSUE TITLE
How much the memory cost when training video generation model?

### ISSUE THREAD

**Issue by csyufei** [cure-lab/MagicDrive#80]
Thank you for your good job!
I input 16 frames, each with 6 view images, and do not use xformers, but When I implement the [sentence](https://github.com/cure-lab/MagicDrive/blob/video/magicdrive/runner/base_runner.py#L537), the memory consumed more than 80G. So is this the reason that I do not use xformers?

**Comment by flymin** [comment]
We have solved your issue through email.
