### ISSUE TITLE
Install environment with CUDA 12

### ISSUE THREAD

**Issue by andrearama** [cure-lab/MagicDrive#81]
Hi all,
great work, and thanks for releasing the code and instruction!

I am trying to install the environment on a server with ~~A100s~~ L40, which have CUDA 12.5 .

The problem with the env you have on the FAQ, is that it uses cuda 11.3, while I think I need to use at least cuda 12.1. 
With cuda 12,  I need to install pytorch 2, which does not have the TH/THC files needed to build/use the mmdet3d you want to build from source. Here is a reference of this error on the mmdetection3d repo [https://github.com/open-mmlab/mmdetection3d/issues/1332](url).

How can I solve this? Do I necessarily need to install mmdet3d from source code? Or what else could I do?

Thanks a lot for your time and availability

**Comment by flymin** [comment]
The env is fine with A100 or A800. We have tested. You do not have to use cuda 12 while cuda 11 is necessary.

**Comment by andrearama** [comment]
Thanks for the prompt answer @flymin !

My apologies for my lapsus, I meant L40 not A100. The cuda version of my L40s (the one I get if I do nvidia-smi) is 12.5

**Comment by flymin** [comment]
I see. L40 need at least cuda 11.8, but I do not find a pre-built torch1.10 with 11.8. You have several options:
1. Compile torch from source
2. Change mmdet3d code for torch2
3. Extract related python code from mmdet3d and drop the  package 

I have tried both 2 and 3, and they work with higher cuda version or torch 2. For 1, I do not know whether there are any version restrictions.

Sorry we do not officially support it in this repo. You have to do the job.

**Comment by andrearama** [comment]
Thanks again for the prompt reply! Will try and let you know

**Comment by andrearama** [comment]
Closing as I do not have this CUDA mismatch issue anymore.
