### ISSUE TITLE
Deprecated diffusion model link

### ISSUE THREAD

**Issue by begumaltunbas** [cure-lab/MagicDrive#84]
Hi,

I assume the stable diff model you used is deprecated since the [link ](https://huggingface.co/runwayml/stable-diffusion-v1-5) doesn't work. Which huggingface model should be used instead? Or do you have the folders in a drive link by any chance?  Thanks in advance.

Best,

**Comment by flymin** [comment]
Maybe you can try this: https://huggingface.co/botp/stable-diffusion-v1-5

**Comment by begumaltunbas** [comment]
Hi sorry for the late answer. I tried the link you shared and demo worked fine. Thanks!
