### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by SunLuyue26** [cure-lab/MagicDrive#85]
Hi, Thank you for your impressive work!

I started training on 8 V100s with all default Settings and the following command, showing that training time for 100 epochs takes one week, is this normal?

**accelerate launch --mixed_precision fp16 --gpu_ids all --num_processes 8 --num_machines 1 --main_process_port 29501 tools/train.py +exp=224x400 runner=8gpus**

![image](https://github.com/user-attachments/assets/f0a1466c-da29-4e6a-adbc-8d8b6317edd0)

**Comment by flymin** [comment]
dup.
video, see #64, #52
image, see #9

**Comment by SunLuyue26** [comment]
> dup. 傻瓜。 video, see #64, #52视频，请参阅 #64 ， #52 image, see #9 image，请参阅 #9

Sorry, but I didn't find the training time for image training in [https://github.com/cure-lab/MagicDrive/issues/9](url) did you put the wrong link?

**Comment by SunLuyue26** [comment]
> dup. video, see #64, #52 image, see #9

Sorry, but I didn't find the training time for image training in #9 . Did you put the wrong link?

**Comment by flymin** [comment]
#14

**Comment by SunLuyue26** [comment]
> #14 show the speed, #9 has solutions for speed up, which is also in our readme.

Thank you for your reply. I noticed that you mentioned that 2s/it speed is relatively normal, is there some problem with my 5s/it speed on the V100?Everything followed the default Settings.

If I try the cache files in h5 format for BEV maps, Will the speed be increased to 2s/it？

**Comment by flymin** [comment]
If you have any follow-ups, please use the existing issues.
