### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by SunLuyue26** [cure-lab/MagicDrive#86]
Hi, Thank you for your impressive work!

I started training on 8 V100s with all default Settings and the following command, showing that training time for 100 epochs takes one week, is this normal?

**accelerate launch --mixed_precision fp16 --gpu_ids all --num_processes 8 --num_machines 1 --main_process_port 29501 tools/train.py +exp=224x400 runner=8gpus**

![image](https://github.com/user-attachments/assets/459268f2-6c62-4978-8ef1-fc63f57458a8)

I noticed that you mentioned that 2s/it speed is relatively normal, is there some problem with my 5s/it speed on the V100?Everything followed the default Settings.

If I try the cache files in h5 format for BEV maps, Will the speed be increased to 2s/it？

**Comment by flymin** [comment]
Duplicate with #14, #9

Let me be specific. If there is existing issues for the same problem, please use it. Opening new issues is really annoying and hard for others to locate the correct place for follow-ups. 

Thank you for your understanding.

**Comment by mzsqw** [comment]
I'm terribly sorry, I think I misunderstood you just now.
