### ISSUE TITLE
force_all_boxes

### ISSUE THREAD

**Issue by XuWuLingYu** [cure-lab/MagicDrive#95]
```
TypeError: __init__() takes from 2 to 14 positional arguments but 15 were given
```

In the file MagicDrive-video/magicdrive/dataset/nuscenes_t_dataset.py the class NuScenesTDataset uses super.__init__(**param) when in the function __init__. But there exists an another parameter `force_all_boxes` which mmdet3d's Nuscenes dataset doesn't have in __init__.Maybe MagicDrive modified mmdet3d's NuscenesDataset?
here is the part code:
```
@DATASETS.register_module()
class NuScenesTDataset(NuScenesDataset):
    def __init__(
        self,
        ann_file,
        pipeline=None,
        dataset_root=None,
        object_classes=None,
        map_classes=None,
        load_interval=1,
        with_velocity=True,
        modality=None,
        box_type_3d="LiDAR",
        filter_empty_gt=True,
        test_mode=False,
        eval_version="detection_cvpr_2019",
        use_valid_flag=False,
        force_all_boxes=False,
        video_length=None,
        start_on_keyframe=True,
        start_on_firstframe=False,
    ) -> None:
        self.video_length = video_length
        self.start_on_keyframe = start_on_keyframe
        self.start_on_firstframe = start_on_firstframe
        super().__init__(
            ann_file, pipeline, dataset_root, object_classes, map_classes,
            load_interval, with_velocity, modality, box_type_3d,
            filter_empty_gt, test_mode, eval_version, use_valid_flag,
            force_all_boxes)
```

Could you please provide the modified version of mmdet3d?thx

**Comment by flymin** [comment]
Did you follow the readme and use mmdet3d from this repo? It is located in `third-party/bevfusion`.

**Comment by XuWuLingYu** [comment]
thanks,it solved.

**Comment by zwang573** [comment]
> thanks,it solved.
TypeError: __init__() takes from 2 to 14 positional arguments but 15 were given
Hi, i also got this error when i try to run test.py with given interpolated annotations, may i ask how u solved this issue?

**Comment by XuWuLingYu** [comment]
Just download the third_party in branch of video,then:
```
cd third_party/bevfusion
pip install -e .
```
Then it works.
