### ISSUE TITLE
about key missing when traing video

### ISSUE THREAD

**Issue by WuZhongQing** [cure-lab/MagicDrive#99]
hi ,i found there has some key miss, when i training 16 frames using rawbox_mv2.0t_0.4.3.yaml , ~  like:
![image](https://github.com/user-attachments/assets/79f6e680-6d1b-4d71-bd29-bbf8a1fe0887)

is this normal ?and how to solve this ~ , hope your reply ~

**Comment by flymin** [comment]
In most cases, it is fine. You should have noticed that they are INFO, which means information for you to check.

**Comment by WuZhongQing** [comment]
> In most cases, it is fine. You should have noticed that they are INFO, which means information for you to check.

thanks~
